---
title: "Summarize Data for ACCURATE"
author: "Yvonne Barkley"
date: "7/3/2021"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r cars}
library(gtsummary)
library(tidyverse)
library(janitor)
library(reshape2)
library(here)
```

```{r}
#### PhD Data ####
# Load basic csv of all ac. encounters used for PHD Chp 3
# data <- read.csv(here::here('./data/SpermiesWithEnvData_20200531.csv')) #not sure when/if this was used...

data <- read.csv(here::here('./data/SpermiesFinal_20210901.csv')) #this was def made in 2021 for ACCURATE by YB


#remove 1642 cruise, data were too noisy
data <- filter(data, survey != 1642)

#add survey year
data$year <- 2010
data$year[data$survey==1303] <- 2013 
data$year[data$survey==1604] <- 2016
data$year[data$survey==1705] <- 2017
data$year[data$survey==1706] <- 2017
# data2 <- dplyr::select(data, last_col(), everything())


####FILTER DATA ####

## filter for LOCALIZED acoustic encounters
dataLoc <- filter(data, loc == 1 & type == 'best'& peak=='A' & itrk == 1)

#----choose one peak and best type (out of min, max, best of peak A or B) with coda
dataCodaLoc <- filter(dataLoc, loc == 1 & type == 'best'& peak=='A', rating >=1, grepl('cd', click_code), sid==999)

#----choose one peak and best type (out of min, max, best of peak A or B) withOUT coda
dataNoCodaLoc <- filter(dataLoc, loc == 1 & type == 'best'& peak=='A', rating >=1, !grepl('cd', click_code), sid==999)


## filter by sightings with & without codas
dataCodaVis <- filter(data, sid<999, rating >=1, grepl('cd', click_code))
dataCoda <- rbind(dataCodaLoc, dataCodaVis)
dataCoda$label <- ifelse(dataCoda$loc == 1, 'localized', 'sighted')

dataNoCodaVis <- filter(data, sid<999, rating >=2, !grepl('cd', click_code))
dataCodaNone <- rbind(dataNoCodaLoc, dataNoCodaVis)
dataCodaNone$label <- ifelse(dataCodaNone$loc == 1, 'localized', 'sighted')

#### Tables ####
#with janitor #USE THIS ONE  
dataCodaLoc %>% tabyl(click_code, year) #localized only

tabylCoda <- dataCoda %>% tabyl(click_code, year, label) %>%
  adorn_totals(where = c("row", "col"))

tabylCodaNone <- dataCodaNone %>% tabyl(click_code, year, label) %>%
  adorn_totals(where = c("row", "col"))

#combine lists
tabylCodaAll <- mapply(rbind, tabylCoda, tabylCodaNone, SIMPLIFY = FALSE)

#save lists
write.csv(tabylCodaAll, here::here('./data/Spermie Data-2021-TotalTabyls.csv'), row.names = FALSE )



# bin the group sizes separately for sighted data separately for coda/no coda
# dataVisCoda <- filter(dataCoda, label == 'sighted')
# dataVisCoda$grpsizebin <- cut(dataVisCoda$grpsize, 5, include.lowest = TRUE)
# 
# dataVisCodaNone <- filter(dataCodaNone, label == 'sighted')
# dataVisCodaNone$grpsizebin <- cut(dataVisCodaNone$grpsize, 5, include.lowest = TRUE)
# 
# tabylVisCoda <- dataVisCoda %>% tabyl(click_code, grpsizebin) %>%
#   adorn_totals(where = c("row", "col"))
# 
# tabylVisCodaNone <- dataVisCodaNone %>% tabyl(click_code, grpsizebin) %>%
#   adorn_totals(where = c("row", "col"))


## OR ##
# separate sighted data and make column for coda/no coda, then bin all group sizes

dataVisCoda <- filter(dataCoda, label == 'sighted')
dataVisCoda$clickbin <- 'coda'

dataVisCodaNone <- filter(dataCodaNone, label == 'sighted')
dataVisCodaNone$clickbin <- 'no_coda'

dataVis <- bind_rows(dataVisCoda, dataVisCodaNone)
dataVis$grpsizebin <- cut(dataVis$grpsize, 5, include.lowest = TRUE)

tabylVis <- dataVis %>% tabyl(click_code, grpsizebin, clickbin) %>%
  adorn_totals(where = c("row", "col"))

# #combine lists
# tabylCodaVisAll <- mapply(rbind,tabylVisCoda,tabylVisCodaNone, SIMPLIFY = FALSE)

#save lists
write.csv(tabylVis, here::here('./data/Spermie Data-2021-TotalTabylVis.csv'), row.names = FALSE )

#graphically present data by group size bins
p = ggplot(data=dataVis,
       mapping = aes(x=grpsizebin, fill = clickbin)) +
  geom_bar(position = 'dodge') +
  xlab("Group Size Bins") +
  ylab("Number of Encounters") +
  ggtitle("Binned Group Sizes by Codas/No Codas") + 
  scale_fill_manual(name="",
                         labels=c("Codas", "No Codas"),
                      values=c("purple1", "yellowgreen"))  +
  theme(legend.text = element_text(size = 20),
        axis.title.x = element_text(size=20),
           axis.text.x  = element_text(size=16),
        axis.title.y = element_text(size=20),
           axis.text.y  = element_text(size=16),
        plot.title = element_text(size=25))

#WITHIN Groups < 10, no codas

dataVis10 <- filter(dataVis, grpsize <= 10, clickbin=='no_coda')

dataVis2 <- filter(dataVis, grpsize < 2, clickbin=='no_coda')

p=ggplot(data=dataVis10,
       mapping = aes(x=grpsize, fill = click_code)) +
  geom_histogram() +
  xlab("Group Size") +
  ylab("Number of Encounters") +
  ggtitle("Group Sizes < 10, No Codas")  +
  
scale_fill_manual(name="",
                         labels=c("Creaks / Regular / Slow", "Regular", "Regular / Slow", "Slow"),
                      values=c("yellowgreen", "#2e86ab", "#f0803c", "purple1")) +
  theme(legend.text = element_text(size = 16),
        axis.title.x = element_text(size=20),
           axis.text.x  = element_text(size=16),
        axis.title.y = element_text(size=20),
           axis.text.y  = element_text(size=16),
        plot.title = element_text(size=25))


#### For all 'No Coda' groups, what kind of clicks are present? #####

pNoCoda <- ggplot(data=dataCodaNone,
       mapping = aes(x=click_code, fill = label)) +
  geom_bar(position = 'dodge') +
 xlab("Click Type") +
  ylab("Number of Encounters") +
  ggtitle("Click Types - No Codas") + 
  scale_fill_manual(name="",
                         labels=c("Localized", "Sighted"),
                      values=c("#2e86ab", "#f0803c"))  +
  theme(legend.text = element_text(size = 20),
        axis.title.x = element_text(size=20),
           axis.text.x  = element_text(size=16),
        axis.title.y = element_text(size=20),
           axis.text.y  = element_text(size=16),
        plot.title = element_text(size=25))


pCoda <- ggplot(data=dataCoda,
       mapping = aes(x=click_code, fill = label)) +
  geom_bar(position = 'dodge') +
 xlab("Click Type") +
  ylab("Number of Encounters") +
  ggtitle("Click Types - With Codas") + 
  scale_fill_manual(name="",
                         labels=c("Localized", "Sighted"),
                      values=c("#2e86ab", "#f0803c"))  +
  theme(legend.text = element_text(size = 20),
        axis.title.x = element_text(size=20),
           axis.text.x  = element_text(size=16),
        axis.title.y = element_text(size=20),
           axis.text.y  = element_text(size=16),
        plot.title = element_text(size=25))

```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.


#Plot Localized vs Sighted - NO CODA
```{r}

ggplot(data=dataCodaNone,
       mapping = aes(x=click_code, fill = label)) +
  geom_bar(position = 'dodge') +
 xlab("Click Type") +
  ylab("Number of Encounters") +
  ggtitle("Click Types - No Codas") + 
  scale_fill_manual(name="",
                         labels=c("Localized", "Sighted"),
                      values=c("#2e86ab", "#f0803c"))  +
  theme(legend.text = element_text(size = 20),
        axis.title.x = element_text(size=20),
           axis.text.x  = element_text(size=16),
        axis.title.y = element_text(size=20),
           axis.text.y  = element_text(size=16),
        plot.title = element_text(size=25))


```

#All Acoustics Only & Sighted - NO CODA
```{r}

#convert negative distances to normal distances
dataCodaNone$dist <- ifelse(dataCodaNone$pdist <0, dataCodaNone$pdist*(-1), dataCodaNone$pdist)

#### CLOSE WHALES - ALL ####
#plotting only whales less than 4 km away
dataCloseWhales <- dataCodaNone %>% dplyr::filter(dist <= 5, rating >1) %>%
  select(ID, survey, acid, sid, UTC, lat, lon, nclk, minutes, grpsize, click_code, array, year, label, dist, rating)

write.csv(dataCloseWhales, here::here('./data/ACCURATE-CloseWhales5km.csv'), row.names = FALSE )

#Simple histogram of close whales by click type
ggplot(data=dataCloseWhales,
       mapping = aes(x=click_code)) +#, fill = label)) +
  geom_bar(position = 'dodge') +
 xlab("Click Type") +
  ylab("Number of Encounters") +
  ggtitle("Whales < 4km away") + 
  
  theme(legend.text = element_text(size = 20),
        axis.title.x = element_text(size=20),
           axis.text.x  = element_text(size=16),
        axis.title.y = element_text(size=20),
           axis.text.y  = element_text(size=16),
        plot.title = element_text(size=25)) #+
# scale_fill_manual(name="",
#                          labels=c("Localized", "Sighted"),
#                       values=c("#2e86ab", "#f0803c"))  +

## CLOSE WHALES - SIGHTED ####
dataCloseVis <- filter(dataCloseWhales, sid <999)

dataCloseVis$grpsizebin <- cut(dataCloseVis$grpsize, 10, include.lowest = TRUE)

### Plot group size bins for close whales < 4km ####

ggplot(data=dataCloseVis,
       mapping = aes(x=grpsize, fill = click_code)) +
  geom_histogram(binwidth = 2) +
  xlab("Group Size") +
  ylab("Number of Encounters") +
  ggtitle("Group Sizes for Sighted Whales < 4km (no codas)") + 
  scale_fill_manual(name="",
                          labels= c("Creaks / Regular", "Creaks / Regular / Slow", "Regular / Slow", "Slow"),
                      values=c("yellowgreen", "#2e86ab", "#f0803c", "purple1"))  +
  theme(legend.text = element_text(size = 15),
        axis.title.x = element_text(size=15),
           axis.text.x  = element_text(size=16),
        axis.title.y = element_text(size=15),
           axis.text.y  = element_text(size=16),
        plot.title = element_text(size=20))

##CLOSE WHALES - LOCALIZED ####

dataCloseLoc <- filter(dataCloseWhales, sid==999)

ggplot(data=dataCloseLoc,
       mapping = aes(x=click_code, fill=click_code)) +
  geom_bar() +
 xlab("Click Type") +
  ylab("Number of Encounters") +
  ggtitle("Click Types for Acoustic-Only Whales < 4km (no codas)") + 
  scale_fill_manual(name="",
                          labels= c("Creaks / Regular", "Regular", "Regular / Slow", "Slow"),
                      values=c("yellowgreen", "deepskyblue", "#f0803c", "purple1")) +
 
  theme(legend.text = element_text(size = 15),
        axis.title.x = element_text(size=15),
           axis.text.x  = element_text(size=16),
        axis.title.y = element_text(size=15),
           axis.text.y  = element_text(size=16),
        plot.title = element_text(size=20))

```
```{r}
#### FAR WHALES - ALL ####

dataFarWhales <- dataCodaNone %>% dplyr::filter(dist > 5, rating >1) %>%
  select(ID, survey, acid, sid, UTC, lat, lon, nclk, minutes, grpsize, click_code, array, year, label, dist, rating)

write.csv(dataFarWhales, here::here('./data/ACCURATE-FarWhales.csv'), row.names = FALSE )


```


#UNLOCALIZED DATA with CODA
```{r}
data2 <- read.csv(here::here('./data/SpermiesFinal_20200919.csv'))

dataNoLoc <- filter(data2, loc==0 & sid==999)

#how many non-localized have codas?

dataCodaNoLoc <- filter(dataNoLoc, grepl('cd', click_code), sid==999)
dataNoCodaNoLoc <- filter(dataNoLoc, !grepl('cd', click_code), sid==999)

dataNoLoc %>% tabyl(click_code, survey)
```


#NONACOUSTIC DATA
```{r}
data2 <- read.csv(here::here('./data/SpermiesFinal_20200919.csv'))

dataNoAc <- filter(data2, acid==999, survey != 1642)
ggplot(data=dataNoAc,
       mapping = aes(x=grpsize)) +
  geom_histogram(binwidth = 1) +
  xlab("Group Size") +
  ylab("Number of Encounters")


#how many non-localized have codas?

dataCodaNoLoc <- filter(dataNoLoc, grepl('cd', click_code), sid==999)
dataNoCodaNoLoc <- filter(dataNoLoc, !grepl('cd', click_code), sid==999)

dataNoLoc %>% tabyl(click_code, survey)
```





Other table methods
```{r}
## OTHER TABLE METHODS ##

#Table by year
#with gtsummary
dataCodaLoc %>%
  select(click_code, year) %>%
  tbl_summary(by = year,
              missing = 'no', percent = "cell") %>%
  modify_spanning_header(all_stat_cols() ~ "**Localized 'Good' Acoustic Encounters**")%>% add_n()#%>%
  bold_labels()
  
  
dataCoda %>% filter(label == 'localized') %>%
  tabyl(click_code, year) %>%
  # adorn_totals(c("row", "col"), name='Total Encounters') %>%
  adorn_title("combined", row_name = 'Click Type', col_name = 'Survey Year') %>%
  knitr::kable()  
  
  
```

